apps/twitterclone_web/lib/twitterclone_web/router.ex
defmodule TwittercloneWeb.Router do
  use TwittercloneWeb, :router

  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TwittercloneWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NavigationHistory.Tracker
    plug TwittercloneWeb.Plugs.Locale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :api_auth do
    plug :accepts, ["json"]
    plug TwittercloneWeb.Plugs.ApiKeyAuthorizationPlug
  end

  scope "/", TwittercloneWeb do
    pipe_through [:browser, :auth]

    get "/login", SessionController, :new
    get "/login/sub", SessionController, :login_sub
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout


    resources "/users", UserController
    get "/twats/:id", TwatController, :show
    get "/profile/:user_id", ProfileController, :profile
    get "/follower/:id", FollowerController, :show
    get "/following/:user_id", FollowerController, :following
    get "/followers/:user_id", FollowerController, :followers

    get "/", PageController, :index
    get "/test", PageController, :test
    get "/unauthorized", PageController, :unauthorized
    get "/error/:errorcode/:error", PageController, :error


    live "/live", LiveController
    get "/auth/google/callback/", GoogleAuthController, :index
    live "/live/username_picker", LiveUsernamePicker
  end


  scope "/", TwittercloneWeb do
    pipe_through [:browser, :auth,  :allowed_for_users]
    get "/welcome", PageController, :welcome

    get "/profile", ProfileController, :myprofile
    get "/feed", ProfileController, :feed
    get "/twat", ProfileController, :newtwat
    post "/twat", ProfileController, :createtwat
    get "/profile/update_picture_url", ProfileController, :update_picture_url



    get "/twats/:id/edit", TwatController, :edit
    patch "/twats/:id", TwatController, :update
    delete "/twats/:id", TwatController, :delete


    post "/comment/:twat_id", ProfileController, :createcomment

    get "/gen_api_key", APIController, :generate

    post "/follow/:user_id/:follower_id", ProfileController, :follow
    post "/unfollow/:user_id/:follower_id", ProfileController, :unfollow

    get "/room/new", RoomController, :new
    post "/room/create", RoomController, :create

    live "/live/room/new", LiveCreateRoom
    live "/rooms/:room_id", LiveRoom
    live "/search", LiveSearch


  end

  scope "/", TwittercloneWeb do
    pipe_through [:browser, :auth,  :allowed_for_admins]
    get "/twats", TwatController, :index

    live_dashboard "/dashboard", metrics: TwittercloneWeb.Telemetry

  end

  scope "/api", TwittercloneWeb do
    pipe_through [:api]
    resources "/users", UserAPIController, except: [:update, :delete]
    get "/twats", TwatAPIController, :index
    get "/twats/:id", TwatAPIController, :show
    resources "/comments", CommentAPIController, except: [:update, :create, :delete]

    pipe_through [:api_auth]
    put "/users/:id", UserAPIController, :update
    delete "/users/:id", UserAPIController, :delete
    get "/users+/:id", UserAPIController, :adminshow

    post "/twats", TwatAPIController, :create
    delete "/twats/:id", TwatAPIController, :delete

    post "/comments", CommentAPIController, :create
    delete "/comments/:id", CommentAPIController, :delete

  end

  pipeline :auth do
    plug TwittercloneWeb.Pipeline
    plug TwittercloneWeb.Plugs.CurrentUserPlug
    plug TwittercloneWeb.Plugs.Protection
  end

  pipeline :allowed_for_users do
    plug TwittercloneWeb.Plugs.AuthorizationPlug, ["Admin", "Manager", "User"]
    plug TwittercloneWeb.Plugs.LiveRedirectPlug
  end

  pipeline :allowed_for_managers do
    plug TwittercloneWeb.Plugs.AuthorizationPlug, ["Admin", "Manager"]
  end

  pipeline :allowed_for_admins do
    plug TwittercloneWeb.Plugs.AuthorizationPlug, ["Admin"]
  end

    # modified AuthorizationPlug to make this unnecesary
  # pipeline :ensure_auth do
  #   plug Guardian.Plug.EnsureAuthenticated
  # end

  # Other scopes may use custom stacks.
  # scope "/api", TwittercloneWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do


    scope "/" do
      pipe_through :browser


    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

apps/twitterclone_web/lib/twitterclone_web/templates/page/error.html.heex
<div class="m-8">
    <%= if assigns[:error] do %>
        <div class="alert alert-danger">
            <p> <%= @error %></p>
        </div>
    <% end %> 
    <div class="bg-lightdark p-5 rounded-xl mt-10 shadow-xl grid grid-cols-2 gap-4 justify-items-stretch" >

        <%= link to: Routes.page_path(@conn, :index) do %>
            <div class="p-5 text-center bg-deepdark  rounded-xl">
                <p><%= gettext("Home") %></p>
            </div>
        <% end %>
        
        <%= link to: NavigationHistory.last_path(@conn) do %>
            <div class="p-5 text-center bg-deepdark  rounded-xl">
                <p><%= gettext("Back") %></p>
            </div>
        <% end %>
    </div>
</div>

apps/twitterclone_web/lib/twitterclone_web/templates/page/index.html.heex
<div class="px-10">

  <section class=" text-center bg-lightdark pt-20 pb-14 my-5 rounded-xl shadow-xl ">
    <h1 class="text-6xl"><%= gettext "Welcome to %{name}!", name: "Twatter" %></h1>
    <p class="text-3xl pt-10"><%= gettext "Not owned by %{elon}", elon: "Elon Musk" %> </p>
  </section>
  
  <%= if assigns[:error] do %>
      <div class=" bg-red-500 p-5 rounded-xl shadow-xl">
        <p> <%= @error %></p>
      </div>
    <% end %>
  
  <div class="bg-lightdark p-5 rounded-xl shadow-xl mt-10  grid grid-cols-2 justify-items-center">
    <%= if @current_user do %>
      <p>Hello  <%= @current_user.user_id %>!</p>
      <p>Role:  <%= @current_user.role %> </p>

      <%= link to: Routes.session_path(@conn, :logout) do %>
        <div class="p-5 bg-deepdark rounded-xl shadow-xl">
          <p><%= gettext("Sign out") %></p>
        </div>
      <% end %>

      <%= link to: Routes.profile_path(@conn, :profile, @current_user.user_id) do %>
        <div class="p-5 bg-deepdark rounded-xl shadow-xl">
          <p><%= gettext("Profile") %></p>
        </div>
      <% end %>
    
    <% else %>

      <div class="col-span-2 flex flex-col space-y-5">
        <div class=" rounded-xl text-center text-fancyclr  shadow-md bg-dark p-5  " >
          <span class="bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-violet-400">
            Log in to do all the things
          </span>
        </div>
  
        <div class="flex flex-row justify-between">
          <%= link to: Routes.session_path(@conn, :new) do %>
            <div class="p-5 bg-deepdark rounded-xl shadow-xl">
              <p><%= gettext("Sign in") %></p>
            </div>
          <% end %>
    
          <%= link to: Routes.user_path(@conn, :new) do %>
            <div class="p-5 bg-deepdark rounded-xl shadow-xl">
              <p><%= gettext("Register") %></p>
            </div>
          <% end %>
        </div>

        <%= link to: @oauth_google_url do %>
            <div class="p-5 bg-blue-600 rounded-xl shadow-xl flex flex-row justify-center " >
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/240px-Google_%22G%22_Logo.svg.png" alt="Profile" style="width:24px;height:24px;">
                <p class="pl-5 text-center font-bold align-middle" > <%= gettext("Sign in with Google") %></p>
            </div>
          <% end %>
      </div>
    <% end %>
  </div>
</div>  

apps/twitterclone_web/lib/twitterclone_web/templates/page/welcome.html.heex
<div class="px-20">

  <section class=" text-center bg-lightdark pt-20 pb-14 my-5 rounded-xl shadow-xl">
    <h1 class="text-5xl">Succesfully completed oath login</h1>
  </section>
  
  <%= if assigns[:error] do %>
      <div class=" bg-red-500 p-5 rounded-xl">
        <p> <%= @error %></p>
      </div>
  <% end %>
  
  

</div>  