apps/twitterclone_web/lib/twitterclone_web/router.ex
defmodule TwittercloneWeb.Router do
  use TwittercloneWeb, :router

  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TwittercloneWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NavigationHistory.Tracker
    plug TwittercloneWeb.Plugs.Locale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :api_auth do
    plug :accepts, ["json"]
    plug TwittercloneWeb.Plugs.ApiKeyAuthorizationPlug
  end

  scope "/", TwittercloneWeb do
    pipe_through [:browser, :auth]

    get "/login", SessionController, :new
    get "/login/sub", SessionController, :login_sub
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout


    resources "/users", UserController
    get "/twats/:id", TwatController, :show
    get "/profile/:user_id", ProfileController, :profile
    get "/follower/:id", FollowerController, :show
    get "/following/:user_id", FollowerController, :following
    get "/followers/:user_id", FollowerController, :followers

    get "/", PageController, :index
    get "/test", PageController, :test
    get "/unauthorized", PageController, :unauthorized
    get "/error/:errorcode/:error", PageController, :error


    live "/live", LiveController
    get "/auth/google/callback/", GoogleAuthController, :index
    live "/live/username_picker", LiveUsernamePicker
  end


  scope "/", TwittercloneWeb do
    pipe_through [:browser, :auth,  :allowed_for_users]
    get "/welcome", PageController, :welcome

    get "/profile", ProfileController, :myprofile
    get "/feed", ProfileController, :feed
    get "/twat", ProfileController, :newtwat
    post "/twat", ProfileController, :createtwat
    get "/profile/update_picture_url", ProfileController, :update_picture_url



    get "/twats/:id/edit", TwatController, :edit
    patch "/twats/:id", TwatController, :update
    delete "/twats/:id", TwatController, :delete


    post "/comment/:twat_id", ProfileController, :createcomment

    get "/gen_api_key", APIController, :generate

    post "/follow/:user_id/:follower_id", ProfileController, :follow
    post "/unfollow/:user_id/:follower_id", ProfileController, :unfollow

    get "/room/new", RoomController, :new
    post "/room/create", RoomController, :create

    live "/live/room/new", LiveCreateRoom
    live "/rooms/:room_id", LiveRoom
    live "/search", LiveSearch


  end

  scope "/", TwittercloneWeb do
    pipe_through [:browser, :auth,  :allowed_for_admins]
    get "/twats", TwatController, :index

    live_dashboard "/dashboard", metrics: TwittercloneWeb.Telemetry

  end

  scope "/api", TwittercloneWeb do
    pipe_through [:api]
    resources "/users", UserAPIController, except: [:update, :delete]
    get "/twats", TwatAPIController, :index
    get "/twats/:id", TwatAPIController, :show
    resources "/comments", CommentAPIController, except: [:update, :create, :delete]

    pipe_through [:api_auth]
    put "/users/:id", UserAPIController, :update
    delete "/users/:id", UserAPIController, :delete
    get "/users+/:id", UserAPIController, :adminshow

    post "/twats", TwatAPIController, :create
    delete "/twats/:id", TwatAPIController, :delete

    post "/comments", CommentAPIController, :create
    delete "/comments/:id", CommentAPIController, :delete

  end

  pipeline :auth do
    plug TwittercloneWeb.Pipeline
    plug TwittercloneWeb.Plugs.CurrentUserPlug
    plug TwittercloneWeb.Plugs.Protection
  end

  pipeline :allowed_for_users do
    plug TwittercloneWeb.Plugs.AuthorizationPlug, ["Admin", "Manager", "User"]
    plug TwittercloneWeb.Plugs.LiveRedirectPlug
  end

  pipeline :allowed_for_managers do
    plug TwittercloneWeb.Plugs.AuthorizationPlug, ["Admin", "Manager"]
  end

  pipeline :allowed_for_admins do
    plug TwittercloneWeb.Plugs.AuthorizationPlug, ["Admin"]
  end

    # modified AuthorizationPlug to make this unnecesary
  # pipeline :ensure_auth do
  #   plug Guardian.Plug.EnsureAuthenticated
  # end

  # Other scopes may use custom stacks.
  # scope "/api", TwittercloneWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do


    scope "/" do
      pipe_through :browser


    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

apps/twitterclone_web/lib/twitterclone_web/views/layout_view.ex
defmodule TwittercloneWeb.LayoutView do
  use TwittercloneWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}

end

apps/twitterclone_web/lib/twitterclone_web/templates/layout/app.html.heex
<main class="grow flex flex-col min-h-0">
  
  <%= if assigns[:title] do %>
    <div class="from-lightdark m-5 p-5 text-5xl text-center text-textclr font-extrabold rounded-2xl shadow-lg to-gray-700 bg-gradient-to-r">
      <h2><%= @conn.assigns.title %></h2>
    </div>
  <% end %>

  <%= if get_flash(@conn, :info) do %>
    <p class="bg-blue-400 p-5 m-5 rounded-xl shadow-xl" role="alert"><%= get_flash(@conn, :info) %></p>
  <% end %>
  <%= if get_flash(@conn, :error) do %>
    <p class="bg-red-400 p-5 m-5 rounded-xl shadow-xl" role="alert"><%= get_flash(@conn, :error) %></p>
  <% end %>
  <%= @inner_content %>
</main>

apps/twitterclone_web/lib/twitterclone_web/templates/layout/live.html.heex
<main class="grow flex flex-col min-h-0">
  
  <%= @inner_content %>
</main>

apps/twitterclone_web/lib/twitterclone_web/templates/layout/navbutton.html.heex
<div class="p-5 h-fit mt-2 flex-col bg-dark text-deepdark  rounded-lg shadow-md hover:text-textclr focus:outline-none focus:ring focus:ring-white focus:ring-offset-gray-100 focus:ring-offset-4">
    <%= link to: @link do %>
        <span class="sr-only">
            <%= @text %>
        </span>
        <svg class='w-12 h-16 dark:text-black' fill='none' stroke='currentColor' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d={@d}>></path></svg>
        <p class="text-center text-base text-textclr" ><%= @text %></p>    
    <% end %>
</div>

apps/twitterclone_web/lib/twitterclone_web/templates/layout/oldnavbar.html.heex
<!DOCTYPE html>
<html lang="en" >
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Twitterclone", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
      crossorigin="anonymous"
    />
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>

    <!-- sidebar starts -->
    <div class="sidebar">
      <!-- <i class="fab fa-twitter"></i> -->
      <%= link to: Routes.profile_path(@conn, :feed) do %>
      <div class="sidebarOption">
          <span class="material-icons"> home </span>
          <%= gettext("Feed") %>
      </div>
      <% end %> 

      <%= link to: Routes.profile_path(@conn, :myprofile) do %>
      <div class="sidebarOption">
          <span class="material-icons"> perm_identity </span>
          <%= gettext("Profile")%>
      </div>
      <% end %> 
      
      <%= link to: Routes.user_path(@conn, :index) do %>
      <div class="sidebarOption">
          <span class="material-icons"> list_alt </span>
          <%=  gettext("Users")%>
      </div>
      <% end %> 

      <%= link to: Routes.page_path(@conn, :index) do %>
      <div class="sidebarOption">
          <span class="material-icons"> more_horiz </span>
          <%= gettext("Home") %>
      </div>
      <% end %> 

      <%= link to: Routes.room_path(@conn, :new) do %>
        <div class="sidebarOption">
          <span class="material-icons"> more_horiz </span>
          Rooms
        </div>
      <% end %>      

      <%= if assigns[:current_user] do %>
        <%= if @current_user.role == "Admin" do %>
          <%= link to: Routes.twat_path(@conn, :index) do %>
            <div class="sidebarOption">
                <span class="material-icons"> bookmark_border </span>
                <%= gettext("Twats")%>
            </div>
          <% end %>

          <%= link to: Routes.live_dashboard_path(@conn, :home) do %>
            <div class="sidebarOption">
                <span class="material-icons"> bookmark_border </span>
                Dashboard
            </div>
          <% end %>
        <% end %>
        

        <%= button "Twat", to: Routes.profile_path(@conn, :newtwat), method: :get, class: "sidebar__tweet"%>
      <% end %>

      <%= if assigns[:current_user] do %>
          <%= for room <- @current_user.rooms do %>
            <%= link to: "/rooms/#{room.id}" do %>
              <div class="sidebarOption sidebarRoom">
                <%= if Enum.member?(room.newmsg, @current_user.user_id) do %>
                  <b> <p><%= room.name%>   !!</p> </b> 
                <% else %>
                  <p><%= room.name%></p> 
                <% end %>
              </div>
            <% end %>
          <% end %>
      <% end %>

      <div class="languageoptionsdiv">
        <p class="languageoptionheader"> <% gettext("language options") %> language options </p> <!-- idk why gettext isnt working -->
        <div class="languageoptions" >
          <%= for locale <- @available_locales do %>
            <%= link locale, to: "#{@conn.request_path}?locale=#{locale}"%>
          <% end %>
        </div>
      </div>
    </div>
    <!-- sidebar ends -->

    <div class="feed">
      <div class="feed__header">
        <h2>Twatter</h2>
      </div>
      <div style="margin: 10px 5px;">
        <%= @inner_content%>
      </div>
     
    </div>

    

    
    

  </body>
</html>

<!--

<div class="sidebarOption">
        <span class="material-icons"> search </span>
        <h2>Explore</h2>
    </div>

    <div class="sidebarOption">
        <span class="material-icons"> notifications_none </span>
        <h2>Notifications</h2>
    </div>

    <div class="sidebarOption">
        <span class="material-icons"> mail_outline </span>
        <h2>Messages</h2>
    </div>

    <div class="sidebarOption">
        <span class="material-icons"> bookmark_border </span>
        <h2>Bookmarks</h2>
    </div>



    -->

apps/twitterclone_web/lib/twitterclone_web/templates/layout/roombutton.html.heex
<div class="my-5">
    <%= link to: @link do %>
        <div class="my-5 flex whitespace-nowrap p-3 items-center space-x-2 text-indigo-600 transition-colors rounded-lg group hover:bg-indigo-600 hover:text-white">
            <p class="px-5" ><%= @text %></p>
        </div>
    <% end %>
</div>